"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

format = """
$nix_shell\
$directory\
$git_branch\
$git_status\
$rust\
$golang\
$python\
$character"""

[nix_shell]
format = '[$symbol$state( \($name\))]($style) '
symbol = '<nix> '

[line_break]
disabled = true

[rust]
format = '[($toolchain) ]($style)'

[git_branch]
symbol = ""
format = '[\($symbol$branch(:$remote_branch)\)]($style)'
style = 'bold red'

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'red'
ahead = '↑'
behind = '↓'
diverged = '↕'
deleted = '×'

[golang]
format = '[$symbol($version)]($style) '
symbol = 'go '

[python]
format = '[$symbol($version)( \($virtualenv\))]($style) '
symbol = 'py '
